### ISSUE TITLE
Bad repository place

### ISSUE THREAD

**Issue by Neustradamus** [jossef/stonks#1]
Dear @jossef,

It is possible to remove:
- https://github.com/sj57/stonks

Of course before removal, https://github.com/jossef/stonks must be up-to-date before.

After, please move https://github.com/jossef/stonks into https://github.com/sj57?

After, you can fork in your personal account from the organization.

Thanks in advance.

**Comment by jossef** [comment]
that was a temporary fork for testing. Just deleted it.

**Comment by Neustradamus** [comment]
@jossef: Thanks for your quick answer!

Not needed to move this repo into the org?

**Comment by jossef** [comment]
Why? It's on my personal account

**Comment by Neustradamus** [comment]
@jossef: SJ57 is not your project?

**Comment by jossef** [comment]
Yep. Unrelated to this repo. I accidentally forked it over there and deleted the fork once I saw your issue. Thanks anyway
